.catalog:
    name: backen
    version: 1 
    uuid: o1aNXXLW
backen:
      scale: 3
postgres:
     scale: 1
proxy:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000

